spring.application.name=dashboard
#spring.datasource.url=jdbc:postgresql://localhost:5433/luminari-labs-db
spring.datasource.url=jdbc:postgresql://82.25.69.177:5432/luminari-labs-db

#spring.datasource.username=postgres
#spring.datasource.password=dba
spring.datasource.username=tmladmin
spring.datasource.password=TMLsecure_db

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true