spring.application.name=dashboard
#spring.datasource.url=jdbc:postgresql://localhost:5433/luminari-labs-db
spring.datasource.url=jdbc:postgresql://82.25.69.177:5432/luminari-labs-db

#spring.datasource.username=postgres
#spring.datasource.password=dba
spring.datasource.username=tmladmin
spring.datasource.password=TMLsecure_db

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration
google.client.id=

# JWT Configuration
# Secret key for signing JWTs (must be at least 256 bits / 32 characters long)
jwt.secret=7d4022c4f686940a43d9f1f0e4701235b2413a9684126742512f4314142f36d0
# Expiration time in milliseconds (e.g., 86400000 ms = 24 hours)
jwt.expiration=86400000
